import { CurrencyMappings } from "@/_types";
import { Asset } from "@/_enums";

export const currencyPairs: CurrencyMappings = [
    {
        source: "USDC",
        targets: [
            { target: "EUR", ticker: "USDCEUR" },
            { target: "USDT", ticker: "USDCUSDT" },
        ],
    },
    {
        source: "USDT",
        targets: [
            { target: "EUR", ticker: "USDTEUR" },
        ],
    },
    {
        source: "BTC",
        targets: [
            { target: "USDT", ticker: "BTCUSDT" },
            { target: "USDC", ticker: "BTCUSDC" },
            { target: "EUR", ticker: "BTCEUR" },
        ],
    },
    {
        source: "ETH",
        targets: [
            { target: "EUR", ticker: "ETHEUR" },
        ],
    },
    {
        source: "BNB",
        targets: [
            { target: "EUR", ticker: "BNBEUR" },
        ],
    },
];


export const mongoDBDocumentID = "currentRates";

export const env = {
    MONGODB_URL: "mongodb+srv://veriuretimi01:munE2L1goLKGMHY1@interview-striga.s74gt.mongodb.net/?retryWrites=true&w=majority&appName=interview-striga",
    API_KEY: "Bi8kkgXNOaZ6Yj3RmtBzkPvRk0fWz_iKw3cDIOnSSxE=",
    API_SECRET: "ZjVIxeqWWY5tWPYPTvRXvBL0SHxiVo0HP0kipAIJ7SQ=",
    STRIGA_API_BASE_URL: "https:/www.sandbox.striga.com/api/v1",
    USER_ID: "bccae8e7-5a68-455c-9ab7-c578d2012d25"
}

export const accountIds: Record<Asset, string> = {
    [Asset.EUR]: "e6592356de5b0fbf8fee6f5e6e876757",
    [Asset.BTC]: "7ffacb13d761e0a4788aeee61d6bf9ce",
    [Asset.USDC]: "2c7ec2c643455c9f9d9d5cec7bf38863",
    [Asset.USDT]: "b060af3e28a8e6194f7f2fe3e2f4f9f2",
    [Asset.ETH]: "43dc23c43a8942aadabf98a9de7fa25a",
    [Asset.BNB]: "51a6b004342c2dce3de9bde533c1b639",
    [Asset.POL]: "ffdeed893aa305128aad0f80c6324988",
}

export const errorsByCode: Record<string, string> = {
    "00000": "Default Error Code",
    "00002": "The amount is denominated as an integer in the smallest divisible unit of the account base currency (Eg: cents, satoshis or wei)",
    "00012": "Feature not implemented yet",
    "00013": "Internal service error",
    "30000": "Invalid API Key",
    "30002": "Exceeded Email Verification Attempt Count",
    "30003": "Exceeded Mobile Verification Attempt Count",
    "30004": "Invalid Mobile Verification Code",
    "30005": "User does not exist",
    "30006": "Invalid patch user",
    "30007": "User not verified",
    "30008": "User is already verified",
    "30009": "User verification is in progress",
    "30010": "KYC rejected, user cannot retry",
    "30011": "KYC attempt limit exceeded",
    "30030": "Email & Mobile not verified to start KYC",
    "30012": "Invalid Authentication Header",
    "30013": "Invalid request - Card ID & User ID mismatch",
    "30100": "Card not active",
    "30101": "Card does not have a PIN",
    "30014": "Third party API failure",
    "30015": "Invalid card limits",
    "30016": "Card is not of type physical",
    "30017": "Card is already blocked",
    "30018": "Card should be blocked to be unblocked",
    "30019": "3dSecure should be enabled for the card before activating",
    "30020": "3dSecure is already disabled",
    "30021": "3dSecure is not enabled",
    "30022": "Invalid cardId",
    "30023": "Card can be activated only if it is ordered",
    "30024": "Card can be blocked only when the card is activated ( applies to only physical cards)",
    "30025": "Card not be unblocked if the card is blocked with blockType being Lost or Stolen",
    "30026": "Card 3dsecure can not be enables when not in 'ACTIVE' state for cards of type PHYSICAL.",
    "30027": "Card can not be activated if the card is not is status \"Dispatched\"",
    "30028": "Invalid activation code for the physical card",
    "30029": "Card is already activated",
    "30031": "Bad transfer request",
    "30032": "Invalid verification code",
    "30033": "Cannot start KYC",
    "30034": "Non ACTIVE card being linked",
    "30035": "Account has a linked card",
    "30099": "Domain Error",
    "30036": "Please request an OTP before verifying",
    "30037": "Please provide at least one transaction fee to update",
    "30038": "Email cannot be same as existing email",
    "30039": "Email already exists",
    "30040": "Mobile cannot be same as existing mobile",
    "30041": "Mobile already exists",
    "30042": "This route is restricted and cannot be accessed",
    "30043": "User is suspended",
    "30044": "Email/Mobile already verified",
    "30045": "Below Minimum Trade Value",
    "31001": "Invalid IBAN/BIC",
    "31002": "Account not enriched",
    "31003": "Self SEPA transfer",
    "31004": "Insufficient balance",
    "31005": "SEPA destination non-enriched or inactive account",
    "31006": "LN withdrawal in progress",
    "31007": "Self LN transfer",
    "31008": "Exceeded Mobile Resend Count",
    "31010": "Exceeded Email Resend Count",
    "31011": "WalletId not found",
    "31012": "Error occurred while creating the card.",
    "31025": "There was an error while initiating the LN transaction.",
    "31026": "An error occurred while initiating the SEPA transaction.",
    "31027": "Error encountered during instant swap process.",
    "31028": "Please try again later. There are too many attempts?",
    "31029": "Error encountered while sending multi-currency transaction.",
    "31030": "An error occurred while initiating inter-intra transaction.",
    "31031": "Error encountered during processing external service provider.",
    "31032": "An error occurred while initiating on-chain transaction.",
    "31033": "Error encountered while fetching email or mobile expiry details.",
    "31038": "Invalid fee estimate - Please verify configured fee parameters.",
    "31047": "Error accessing the requested resource.",
    "31048": "Account operation has expired.",
    "31055": "Rate limit exceeded.",
    "31062": "Funds cannot be sent in this direction.",
    "31064": "Invalid OTP.",
    "31065": "Too many attempts at 2FA.",
    "31067": "Invalid transaction type specified.",
    "31069": "Mobile number not set for the account.",
    "31073": "Invalid wallet ID provided.",
    "31075": "Invalid user ID provided.",
    "31078": "Invalid withdrawal fee specified.",
    "31079": "Account has already been enriched.",
    "31081": "Error occurred during enrichment process.",
    "31082": "Invalid currency specified.",
    "31083": "User not found in the system.",
    "31088": "Trade value is below the minimum allowed.",
    "31090": "Insufficient balance for the transaction.",
    "31092": "Error occurred while creating user account.",
    "31093": "Error occurred while patching user data.",
    "31094": "Error encountered while sending verification code.",
    "32011": "Card country not supported",
    "32012": "Card creation limit reached",
    "32013": "accountIdToLink is required when a fee is configured",
    "32014": "Invalid accountId",
    "32015": "Mobile number already exists",
    "32016": "Invalid mobile number",
    "32017": "User is terminated",
    "41001": "Invalid currency/network pair",
    "41002": "Address already whitelisted",
    "41003": "Address cannot be whitelisted",
    "41004": "Address not whitelisted",
    "41005": "Invalid destination address on send",
    "41006": "Invalid address",
    "41007": "DeFi not enabled on account",
    "41008": "Withdrawal fees exceed amount",
    "60001": "User limit exceeded",
};
